package com.chingproyects.sge.pojos;
// Generated 26/11/2017 23:17:37 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Serializable id;
     private String descripcion;
     private String detalle;
     private char estado;
     private Set matriculas = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(Serializable id, String descripcion, String detalle, char estado) {
        this.id = id;
        this.descripcion = descripcion;
        this.detalle = detalle;
        this.estado = estado;
    }
    public Categoria(Serializable id, String descripcion, String detalle, char estado, Set matriculas) {
       this.id = id;
       this.descripcion = descripcion;
       this.detalle = detalle;
       this.estado = estado;
       this.matriculas = matriculas;
    }
   
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(Serializable id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


