package com.chingproyects.sge.pojos;
// Generated 26/11/2017 23:17:37 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Serializable id;
     private SegEntidad segEntidad;
     private String descripcion;
     private Date fechainicio;
     private Date fechafin;
     private Set matriculas = new HashSet(0);

    public Curso() {
    }

	
    public Curso(Serializable id, SegEntidad segEntidad, String descripcion, Date fechainicio, Date fechafin) {
        this.id = id;
        this.segEntidad = segEntidad;
        this.descripcion = descripcion;
        this.fechainicio = fechainicio;
        this.fechafin = fechafin;
    }
    public Curso(Serializable id, SegEntidad segEntidad, String descripcion, Date fechainicio, Date fechafin, Set matriculas) {
       this.id = id;
       this.segEntidad = segEntidad;
       this.descripcion = descripcion;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.matriculas = matriculas;
    }
   
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(Serializable id) {
        this.id = id;
    }
    public SegEntidad getSegEntidad() {
        return this.segEntidad;
    }
    
    public void setSegEntidad(SegEntidad segEntidad) {
        this.segEntidad = segEntidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


