package com.chingproyects.sge.pojos;
// Generated 26/11/2017 23:17:37 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Detallepago generated by hbm2java
 */
public class Detallepago  implements java.io.Serializable {


     private Serializable id;
     private Pago pago;
     private double valor;
     private Date fechapago;
     private Date fechainsercion;

    public Detallepago() {
    }

    public Detallepago(Serializable id, Pago pago, double valor, Date fechapago, Date fechainsercion) {
       this.id = id;
       this.pago = pago;
       this.valor = valor;
       this.fechapago = fechapago;
       this.fechainsercion = fechainsercion;
    }
   
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(Serializable id) {
        this.id = id;
    }
    public Pago getPago() {
        return this.pago;
    }
    
    public void setPago(Pago pago) {
        this.pago = pago;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public Date getFechapago() {
        return this.fechapago;
    }
    
    public void setFechapago(Date fechapago) {
        this.fechapago = fechapago;
    }
    public Date getFechainsercion() {
        return this.fechainsercion;
    }
    
    public void setFechainsercion(Date fechainsercion) {
        this.fechainsercion = fechainsercion;
    }




}


