package com.chingproyects.sge.pojos;
// Generated 26/11/2017 23:17:37 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private Serializable id;
     private Alumno alumno;
     private Categoria categoria;
     private Curso curso;
     private double preciomatricula;
     private double preciomensualidad;
     private Date fechamatricula;
     private int nmensualidades;
     private Set pagos = new HashSet(0);

    public Matricula() {
    }

	
    public Matricula(Serializable id, Alumno alumno, Categoria categoria, Curso curso, double preciomatricula, double preciomensualidad, Date fechamatricula, int nmensualidades) {
        this.id = id;
        this.alumno = alumno;
        this.categoria = categoria;
        this.curso = curso;
        this.preciomatricula = preciomatricula;
        this.preciomensualidad = preciomensualidad;
        this.fechamatricula = fechamatricula;
        this.nmensualidades = nmensualidades;
    }
    public Matricula(Serializable id, Alumno alumno, Categoria categoria, Curso curso, double preciomatricula, double preciomensualidad, Date fechamatricula, int nmensualidades, Set pagos) {
       this.id = id;
       this.alumno = alumno;
       this.categoria = categoria;
       this.curso = curso;
       this.preciomatricula = preciomatricula;
       this.preciomensualidad = preciomensualidad;
       this.fechamatricula = fechamatricula;
       this.nmensualidades = nmensualidades;
       this.pagos = pagos;
    }
   
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(Serializable id) {
        this.id = id;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public double getPreciomatricula() {
        return this.preciomatricula;
    }
    
    public void setPreciomatricula(double preciomatricula) {
        this.preciomatricula = preciomatricula;
    }
    public double getPreciomensualidad() {
        return this.preciomensualidad;
    }
    
    public void setPreciomensualidad(double preciomensualidad) {
        this.preciomensualidad = preciomensualidad;
    }
    public Date getFechamatricula() {
        return this.fechamatricula;
    }
    
    public void setFechamatricula(Date fechamatricula) {
        this.fechamatricula = fechamatricula;
    }
    public int getNmensualidades() {
        return this.nmensualidades;
    }
    
    public void setNmensualidades(int nmensualidades) {
        this.nmensualidades = nmensualidades;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


