package com.chingproyects.sge.pojos;
// Generated 26/11/2017 23:17:37 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private Serializable id;
     private Matricula matricula;
     private Tipovalor tipovalor;
     private double valor;
     private String descripcion;
     private Set detallepagos = new HashSet(0);
     private Set detallepagos_1 = new HashSet(0);

    public Pago() {
    }

	
    public Pago(Serializable id, Matricula matricula, Tipovalor tipovalor, double valor) {
        this.id = id;
        this.matricula = matricula;
        this.tipovalor = tipovalor;
        this.valor = valor;
    }
    public Pago(Serializable id, Matricula matricula, Tipovalor tipovalor, double valor, String descripcion, Set detallepagos, Set detallepagos_1) {
       this.id = id;
       this.matricula = matricula;
       this.tipovalor = tipovalor;
       this.valor = valor;
       this.descripcion = descripcion;
       this.detallepagos = detallepagos;
       this.detallepagos_1 = detallepagos_1;
    }
   
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(Serializable id) {
        this.id = id;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public Tipovalor getTipovalor() {
        return this.tipovalor;
    }
    
    public void setTipovalor(Tipovalor tipovalor) {
        this.tipovalor = tipovalor;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getDetallepagos() {
        return this.detallepagos;
    }
    
    public void setDetallepagos(Set detallepagos) {
        this.detallepagos = detallepagos;
    }
    public Set getDetallepagos_1() {
        return this.detallepagos_1;
    }
    
    public void setDetallepagos_1(Set detallepagos_1) {
        this.detallepagos_1 = detallepagos_1;
    }




}


