package com.chingproyects.sge.pojos;
// Generated 26/11/2017 23:17:37 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * SegEntidad generated by hbm2java
 */
public class SegEntidad  implements java.io.Serializable {


     private Serializable id;
     private String descripcion;
     private String ruc;
     private String direccion;
     private String telefono1;
     private String telefono2;
     private String telefono3;
     private char estado;
     private String ciudad;
     private Set cursos = new HashSet(0);
     private Set segUsuarioentidads = new HashSet(0);

    public SegEntidad() {
    }

	
    public SegEntidad(Serializable id, String descripcion, String ruc, String direccion, String telefono1, String telefono2, String telefono3, char estado, String ciudad) {
        this.id = id;
        this.descripcion = descripcion;
        this.ruc = ruc;
        this.direccion = direccion;
        this.telefono1 = telefono1;
        this.telefono2 = telefono2;
        this.telefono3 = telefono3;
        this.estado = estado;
        this.ciudad = ciudad;
    }
    public SegEntidad(Serializable id, String descripcion, String ruc, String direccion, String telefono1, String telefono2, String telefono3, char estado, String ciudad, Set cursos, Set segUsuarioentidads) {
       this.id = id;
       this.descripcion = descripcion;
       this.ruc = ruc;
       this.direccion = direccion;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.telefono3 = telefono3;
       this.estado = estado;
       this.ciudad = ciudad;
       this.cursos = cursos;
       this.segUsuarioentidads = segUsuarioentidads;
    }
   
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(Serializable id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public String getTelefono3() {
        return this.telefono3;
    }
    
    public void setTelefono3(String telefono3) {
        this.telefono3 = telefono3;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }
    public Set getSegUsuarioentidads() {
        return this.segUsuarioentidads;
    }
    
    public void setSegUsuarioentidads(Set segUsuarioentidads) {
        this.segUsuarioentidads = segUsuarioentidads;
    }




}


