package com.chingproyects.sge.pojos;
// Generated 26/11/2017 23:17:37 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * SegPermiso generated by hbm2java
 */
public class SegPermiso  implements java.io.Serializable {


     private Serializable id;
     private String descripcion;
     private String valor;
     private char estado;
     private Set segPermisorols = new HashSet(0);

    public SegPermiso() {
    }

	
    public SegPermiso(Serializable id, String descripcion, String valor, char estado) {
        this.id = id;
        this.descripcion = descripcion;
        this.valor = valor;
        this.estado = estado;
    }
    public SegPermiso(Serializable id, String descripcion, String valor, char estado, Set segPermisorols) {
       this.id = id;
       this.descripcion = descripcion;
       this.valor = valor;
       this.estado = estado;
       this.segPermisorols = segPermisorols;
    }
   
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(Serializable id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set getSegPermisorols() {
        return this.segPermisorols;
    }
    
    public void setSegPermisorols(Set segPermisorols) {
        this.segPermisorols = segPermisorols;
    }




}


