package com.chingproyects.sge.pojos;
// Generated 26/11/2017 23:17:37 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * SegPermisorol generated by hbm2java
 */
public class SegPermisorol  implements java.io.Serializable {


     private Serializable id;
     private SegPermiso segPermiso;
     private SegRol segRol;
     private char estado;

    public SegPermisorol() {
    }

    public SegPermisorol(Serializable id, SegPermiso segPermiso, SegRol segRol, char estado) {
       this.id = id;
       this.segPermiso = segPermiso;
       this.segRol = segRol;
       this.estado = estado;
    }
   
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(Serializable id) {
        this.id = id;
    }
    public SegPermiso getSegPermiso() {
        return this.segPermiso;
    }
    
    public void setSegPermiso(SegPermiso segPermiso) {
        this.segPermiso = segPermiso;
    }
    public SegRol getSegRol() {
        return this.segRol;
    }
    
    public void setSegRol(SegRol segRol) {
        this.segRol = segRol;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }




}


