package com.chingproyects.sge.pojos;
// Generated 26/11/2017 23:17:37 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * SegRol generated by hbm2java
 */
public class SegRol  implements java.io.Serializable {


     private Serializable id;
     private String descripcion;
     private char estado;
     private String detalle;
     private Set segPermisorols = new HashSet(0);
     private Set segUsuarios = new HashSet(0);

    public SegRol() {
    }

	
    public SegRol(Serializable id, String descripcion, char estado, String detalle) {
        this.id = id;
        this.descripcion = descripcion;
        this.estado = estado;
        this.detalle = detalle;
    }
    public SegRol(Serializable id, String descripcion, char estado, String detalle, Set segPermisorols, Set segUsuarios) {
       this.id = id;
       this.descripcion = descripcion;
       this.estado = estado;
       this.detalle = detalle;
       this.segPermisorols = segPermisorols;
       this.segUsuarios = segUsuarios;
    }
   
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(Serializable id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Set getSegPermisorols() {
        return this.segPermisorols;
    }
    
    public void setSegPermisorols(Set segPermisorols) {
        this.segPermisorols = segPermisorols;
    }
    public Set getSegUsuarios() {
        return this.segUsuarios;
    }
    
    public void setSegUsuarios(Set segUsuarios) {
        this.segUsuarios = segUsuarios;
    }




}


