package com.chingproyects.sge.pojos;
// Generated 26/11/2017 23:17:37 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * SegUsuarioentidad generated by hbm2java
 */
public class SegUsuarioentidad  implements java.io.Serializable {


     private Serializable id;
     private SegEntidad segEntidad;
     private SegUsuario segUsuario;

    public SegUsuarioentidad() {
    }

	
    public SegUsuarioentidad(Serializable id) {
        this.id = id;
    }
    public SegUsuarioentidad(Serializable id, SegEntidad segEntidad, SegUsuario segUsuario) {
       this.id = id;
       this.segEntidad = segEntidad;
       this.segUsuario = segUsuario;
    }
   
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(Serializable id) {
        this.id = id;
    }
    public SegEntidad getSegEntidad() {
        return this.segEntidad;
    }
    
    public void setSegEntidad(SegEntidad segEntidad) {
        this.segEntidad = segEntidad;
    }
    public SegUsuario getSegUsuario() {
        return this.segUsuario;
    }
    
    public void setSegUsuario(SegUsuario segUsuario) {
        this.segUsuario = segUsuario;
    }




}


