package com.chingproyects.sge.pojos;
// Generated 26/11/2017 23:17:37 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * SegUsuario generated by hbm2java
 */
public class SegUsuario  implements java.io.Serializable {


     private Serializable id;
     private SegRol segRol;
     private String nombres;
     private String apellidos;
     private String cedula;
     private String usuario;
     private String clave;
     private String telefono1;
     private String telefono2;
     private String direccion;
     private String sexo;
     private String fechanac;
     private char estado;
     private Set segUsuarioentidads = new HashSet(0);

    public SegUsuario() {
    }

	
    public SegUsuario(Serializable id, SegRol segRol, String nombres, String apellidos, String cedula, String usuario, String clave, String telefono1, String telefono2, String direccion, String sexo, String fechanac, char estado) {
        this.id = id;
        this.segRol = segRol;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.cedula = cedula;
        this.usuario = usuario;
        this.clave = clave;
        this.telefono1 = telefono1;
        this.telefono2 = telefono2;
        this.direccion = direccion;
        this.sexo = sexo;
        this.fechanac = fechanac;
        this.estado = estado;
    }
    public SegUsuario(Serializable id, SegRol segRol, String nombres, String apellidos, String cedula, String usuario, String clave, String telefono1, String telefono2, String direccion, String sexo, String fechanac, char estado, Set segUsuarioentidads) {
       this.id = id;
       this.segRol = segRol;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.cedula = cedula;
       this.usuario = usuario;
       this.clave = clave;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.direccion = direccion;
       this.sexo = sexo;
       this.fechanac = fechanac;
       this.estado = estado;
       this.segUsuarioentidads = segUsuarioentidads;
    }
   
    public Serializable getId() {
        return this.id;
    }
    
    public void setId(Serializable id) {
        this.id = id;
    }
    public SegRol getSegRol() {
        return this.segRol;
    }
    
    public void setSegRol(SegRol segRol) {
        this.segRol = segRol;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getFechanac() {
        return this.fechanac;
    }
    
    public void setFechanac(String fechanac) {
        this.fechanac = fechanac;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set getSegUsuarioentidads() {
        return this.segUsuarioentidads;
    }
    
    public void setSegUsuarioentidads(Set segUsuarioentidads) {
        this.segUsuarioentidads = segUsuarioentidads;
    }




}


